ARG JDK_VERSION
FROM findepi/graalvm:${JDK_VERSION}-native
LABEL maintainer="Piotr Findeisen <piotr.findeisen@gmail.com>"

RUN set -xeu && \
    gu install -c org.graalvm.python && \
    gu install -c org.graalvm.ruby && \
    # Currently not available for 23.0.1
#    gu install -c org.graalvm.R && \
    echo OK

# vim:set ft=dockerfile:
