ARG GRAAL_VERSION
FROM findepi/graalvm:${GRAAL_VERSION}
LABEL maintainer="Piotr Findeisen <piotr.findeisen@gmail.com>"

RUN set -xeu && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
        clang \
        gcc \
        libz-dev \
        llvm \
        && \
    gu install native-image && \
    # Cleanup
    apt-get clean && rm -rf "/var/lib/apt/lists/*" && \
    echo OK

# vim:set ft=dockerfile:
