ARG JDK_VERSION
FROM findepi/graalvm:${JDK_VERSION}
LABEL maintainer="Piotr Findeisen <piotr.findeisen@gmail.com>"

RUN set -xeu && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
        gcc \
        g++ \
        libz-dev \
        && \
    # Cleanup
    apt-get clean && rm -rf "/var/lib/apt/lists/*" && \
    echo OK

# vim:set ft=dockerfile:
